version: '3.9'

services:

  keycloak:
    image: gunnaraccso/keycloak.server:21.1.1
    restart: always
    env_file:
      - ./env/keycloak.env
    # Add 127.0.0.1 keycloak in /etc/hosts
    ports:
      - "9001:9001"
      - "9000:9000"
    command:
      - start-dev
      - --http-port=9000
      - --https-port=9001

  camunda:
    build: .
    ports: 
      - 8080:8080
    env_file:
      - ./env/camunda.env
    depends_on:
      - keycloak
    restart: always
    volumes:
      - ./config/default.yml:/camunda/configuration/default.yml
      - ./config/production.yml:/camunda/configuration/production.yml

