name: Build project with Maven
on:
  pull_request: 
  push: 
  schedule:
  - cron: '2 2 * * 1-5' # run nightly master builds on weekdays

jobs:
  build:
    runs-on: ubuntu-22.04
    services:
      keycloak:
        image: bitnami/keycloak:24.0.3
        env:
          KEYCLOAK_USER: keycloak
          KEYCLOAK_PASSWORD: keycloak1!
          KEYCLOAK_DATABASE_VENDOR: dev-mem
          KEYCLOAK_HTTP_RELATIVE_PATH: /auth
        ports: [ 8080/tcp ]
        options: --health-cmd "curl -Iks http://localhost:8080" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Java setup
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: temurin
    - name: Cache
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # pin@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Run Maven
      env:
        KEYCLOAK_URL: http://localhost:${{ job.services.keycloak.ports[8080] }}/auth
      run: mvn -B clean install com.mycila:license-maven-plugin:check
